version: '3.4'

services:

  gateway:
    image: jwilder/whoami
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=dotnetcore.tk
      - VIRTUAL_PORT=80,8000
    links:
      - appone
      - apptwo
    network_mode: bridge
  
  appone:
    image: ${DOCKER_REGISTRY-}dockerproxyappone
    build:
      context: .
      dockerfile: app1/Docker.Proxy.AppOne/Dockerfile
    network_mode: bridge

  apptwo:
    image: ${DOCKER_REGISTRY-}dockerproxyapptwo
    build:
      context: .
      dockerfile: app2/Docker.Proxy.AppTwo/Dockerfile
    network_mode: bridge

