version: '3.4'

services:
  gateway:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=35.225.70.10
    links:
      - appone
      - apptwo

  appone:
    image: ${DOCKER_REGISTRY-}dockerproxyappone
    build:
      context: .
      dockerfile: app1/Docker.Proxy.AppOne/Dockerfile

  apptwo:
    image: ${DOCKER_REGISTRY-}dockerproxyapptwo
    build:
      context: .
      dockerfile: app2/Docker.Proxy.AppTwo/Dockerfile

